"""
Data schemas and context representations for Module 6 — Local Agentic AI.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime



class ReasoningStep(BaseModel):
    statement: str
    evidence_ids: List[str] = Field(default_factory=list)


class EvidenceReference(BaseModel):
    evidence_id: str
    source_type: str  # alert, case, asset
    source_record_id: Optional[str] = None
    timestamp: Optional[str] = None
    summary: str


class AssessmentContext(BaseModel):
    """
    Deterministic, bounded context object passed to agents.
    Does NOT contain the entire raw database; strictly scoped to the finding,
    associated evidence graph, assurance profile, and relevant telemetry.
    """
    analysis_id: Optional[str] = None
    entity_id: str
    finding: Dict[str, Any]
    supporting_evidence: List[EvidenceReference] = Field(default_factory=list)
    contradictions: List[Dict[str, Any]] = Field(default_factory=list)
    blind_spots: List[Dict[str, Any]] = Field(default_factory=list)
    coverage: Dict[str, Any] = Field(default_factory=dict)
    dependencies: Dict[str, Any] = Field(default_factory=dict)
    limitations: List[str] = Field(default_factory=list)
    analytics: Dict[str, Any] = Field(default_factory=dict)
    valid_evidence_ids: List[str] = Field(default_factory=list)


class AssessmentAgentOutput(BaseModel):
    """
    Structured hypothesis generated by AssessmentAgent.
    """
    agent: str = "assessment_agent"
    hypothesis: str
    finding_confidence: str  # HIGH, MEDIUM, LOW
    assessment_validity: str  # HIGH, CAUTION, LOW, INDETERMINATE
    supporting_evidence: List[str] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    reasoning: List[ReasoningStep] = Field(default_factory=list)
    alternative_explanations: List[str] = Field(default_factory=list)


class ChallengeAgentOutput(BaseModel):
    """
    Structured adversarial critique generated by ChallengeAgent.
    """
    agent: str = "challenge_agent"
    challenge_status: str  # SUPPORTED, WEAKENED, INSUFFICIENT_EVIDENCE, CONTRADICTED
    counter_evidence: List[str] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    blind_spots: List[str] = Field(default_factory=list)
    alternative_explanations: List[str] = Field(default_factory=list)
    severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CRITICAL
    reasoning: List[ReasoningStep] = Field(default_factory=list)


class InvestigationRequestItem(BaseModel):
    type: str  # CASE_MANAGEMENT_EXPORT, TELEMETRY_LOG_EXPORT, ESCALATION_RECORD_SAMPLE, etc.
    reason: str


class InvestigationPlannerOutput(BaseModel):
    """
    Next-best investigation plan generated by InvestigationPlanner.
    """
    agent: str = "investigation_planner"
    recommended_action: str
    evidence_to_request: List[InvestigationRequestItem] = Field(default_factory=list)
    target_scope: Dict[str, Any] = Field(default_factory=dict)
    uncertainty_reduced: List[str] = Field(default_factory=list)
    priority: str = "HIGH"  # HIGH, MEDIUM, LOW
    estimated_review_effort: str = "MEDIUM"  # LOW, MEDIUM, HIGH
    supporting_evidence: List[str] = Field(default_factory=list)


class HumanReviewPackage(BaseModel):
    """
    Consolidated supervisory review package presented to the human examiner.
    """
    run_id: str
    finding_id: str
    entity_id: str
    state: str = "HUMAN_REVIEW_REQUIRED"
    finding_confidence: str
    assessment_validity: str
    assessment_agent_result: AssessmentAgentOutput
    challenge_agent_result: ChallengeAgentOutput
    investigation_planner_result: InvestigationPlannerOutput
    human_decision: Optional[str] = None
    human_notes: Optional[str] = None
    audit_summary: Dict[str, Any] = Field(default_factory=dict)
    disclaimer: str


class HumanDecisionRequest(BaseModel):
    decision: str  # CONFIRMED, REJECTED, MODIFIED, REQUEST_EVIDENCE
    notes: Optional[str] = None
    reviewer: Optional[str] = "Human Examiner"


class AgentRunResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    run_id: str
    finding_id: str
    entity_id: str
    state: str
    mode: str
    assessment_result: Dict[str, Any]
    challenge_result: Dict[str, Any]
    planner_result: Dict[str, Any]
    human_decision: Optional[str] = None
    human_notes: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AgentAuditLogResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    run_id: str
    agent_id: str
    finding_id: str
    timestamp: datetime
    input_context_hash: Optional[str] = None
    model_provider: str
    model_name: str
    prompt_version: str
    output_hash: Optional[str] = None
    referenced_evidence_ids: List[str] = []
    action: str
    status: str
    validation_result: str
    error_message: Optional[str] = None

